# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Rob Lockyer'
tagline:          'Portfolio and Blog'
description:      'Software Developer, Artist'
url:              http://www.roblockyer.com
baseurl:          /hyde

author:
  name:           'Rob Lockyer'
  url:            https://twitter.com/roblockyer

paginate:         5

linkedin_public_url: 'ca.linkedin.com/in/roblockyer'
twitter_username: roblockyer
disqus_shortname: roblockyer

sass:
    style: :compressed