# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Rob Lockyer'
tagline:          'Portfolio and Blog'
description:      'Software Developer, Artist'
search_engine_description: >
  I'm a professional software developer, and amateur
  artist. I make video games, and tools for game developers. 
  I've been doing this for over five years; on projects like Madden,
  and Second Chance Heroes.

url:              http://www.roblockyer.com     

author:
  name:           'Rob Lockyer'
  url:            https://twitter.com/roblockyer

paginate:         5

linkedin_public_url: 'ca.linkedin.com/in/roblockyer'
twitter_username: roblockyer
disqus_shortname: roblockyer

sass:
    style: :compressed
